version: '3.8'

services:
  db:
    image: postgres:15
    container_name: example_postgres
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: springboot_app
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testdb
  #     SPRING_DATASOURCE_USERNAME: postgres
  #     SPRING_DATASOURCE_PASSWORD: postgres
  #   networks:
  #     - backend

volumes:
  postgres_data:

networks:
  backend:
